// <auto-generated />
using Dashboard.DataG.EF.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace Dashboard.DataG.Migrations
{
    [DbContext(typeof(DashboardGenericContext))]
    [Migration("20171104165148_Inheritance")]
    partial class Inheritance
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.BaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseEntity");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.AcquiredKnowledge", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int>("EmployeeId");

                    b.Property<int>("KnowledgeId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("KnowledgeId");

                    b.ToTable("EmployeeKnowledge");

                    b.HasDiscriminator().HasValue("AcquiredKnowledge");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Assignment", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int>("EmployeeId")
                        .HasColumnName("Assignment_EmployeeId");

                    b.Property<string>("JobTitle");

                    b.Property<string>("Location");

                    b.Property<int>("ProjectId");

                    b.Property<DateTime>("StartDate");

                    b.Property<DateTime>("StopDate");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProjectId");

                    b.ToTable("EmployeeProject");

                    b.HasDiscriminator().HasValue("Assignment");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Client", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<string>("ClientName");

                    b.Property<string>("Description");

                    b.Property<int>("LocationId");

                    b.HasIndex("LocationId");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Commitment", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int>("AssigmentId");

                    b.Property<int>("Hours");

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("Commitment_StartDate");

                    b.Property<DateTime>("StopDate")
                        .HasColumnName("Commitment_StopDate");

                    b.HasIndex("AssigmentId");

                    b.ToTable("Commitment");

                    b.HasDiscriminator().HasValue("Commitment");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Employee", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<string>("ImageName");

                    b.Property<string>("ImagePath");

                    b.Property<string>("LastName")
                        .IsRequired();

                    b.Property<string>("PersonNr");

                    b.ToTable("Employee");

                    b.HasDiscriminator().HasValue("Employee");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Knowledge", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<string>("Description")
                        .HasColumnName("Knowledge_Description");

                    b.Property<string>("KnowledgeName");

                    b.ToTable("Knowledge");

                    b.HasDiscriminator().HasValue("Knowledge");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Location", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.ToTable("Location");

                    b.HasDiscriminator().HasValue("Location");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Phase", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<string>("Comments");

                    b.Property<string>("PhaseName");

                    b.Property<int>("ProjectId")
                        .HasColumnName("Phase_ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Phase");

                    b.HasDiscriminator().HasValue("Phase");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Picture", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int?>("EmployeeId")
                        .HasColumnName("Picture_EmployeeId");

                    b.Property<string>("FileName")
                        .IsRequired();

                    b.Property<string>("Title")
                        .IsRequired();

                    b.HasIndex("EmployeeId");

                    b.ToTable("BaseEntity");

                    b.HasDiscriminator().HasValue("Picture");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Project", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int>("ClientId");

                    b.Property<string>("Notes");

                    b.Property<string>("ProjectName")
                        .IsRequired();

                    b.Property<DateTime>("StartDate")
                        .HasColumnName("Project_StartDate");

                    b.Property<DateTime>("StopDate")
                        .HasColumnName("Project_StopDate");

                    b.Property<int>("TimeBudget");

                    b.HasIndex("ClientId");

                    b.ToTable("Project");

                    b.HasDiscriminator().HasValue("Project");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Task", b =>
                {
                    b.HasBaseType("Dashboard.EntitiesG.EntitiesRev.BaseEntity");

                    b.Property<int>("PhaseId");

                    b.Property<string>("TaskName");

                    b.HasIndex("PhaseId");

                    b.ToTable("Task");

                    b.HasDiscriminator().HasValue("Task");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.AcquiredKnowledge", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Employee", "Employee")
                        .WithMany("AcquiredKnowledges")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Knowledge", "Knowledge")
                        .WithMany("AcquiredKnowledges")
                        .HasForeignKey("KnowledgeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Assignment", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Employee", "Employee")
                        .WithMany("Assignments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Project", "Project")
                        .WithMany("Assignments")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Client", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Location", "Location")
                        .WithMany("Clients")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Commitment", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Assignment", "Assignment")
                        .WithMany("Commitments")
                        .HasForeignKey("AssigmentId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Phase", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Project", "Project")
                        .WithMany("Phases")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Picture", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Project", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Dashboard.EntitiesG.EntitiesRev.Task", b =>
                {
                    b.HasOne("Dashboard.EntitiesG.EntitiesRev.Phase", "Phase")
                        .WithMany("Tasks")
                        .HasForeignKey("PhaseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
